site_name: D&S Documentation
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Page tree
nav:
  - Home: index.md
  - Constituents: 
    - constituents/index.md
    - Defaults: constituents/defaults.md
    - Receipts / Acknowledgements: constituents/receipts.md
    - Deceased Constituents: constituents/deceased.md
    - Honor / Memorial: constituents/honor.md
    - Merges: constituents/merges.md
  - Lockbox:
    - lockbox/index.md
    - Getting Started: lockbox/import.md
    - Gift Entry: lockbox/gift-entry.md
    - Commit and Audit: lockbox/commit.md
  - In House:
    - in-house/index.md
    - Getting Started: in-house/setup.md
    - Gift Entry: in-house/gift-entry.md
    - Commit and Audit: in-house/commit.md
  - Classy: classy/index.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  # - toc:
  #     permalink: true
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  - pymdownx.details
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #     normalize_issue_symbols: true
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.snippets:
  #     auto_append:
  #       - includes/mkdocs.md
  #       - includes/abbreviations.md
  - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  #     combine_header_slug: true
  #     slugify:
  #       kwds:
  #         case: lower
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
